name: Check for Vulnerabilities
on:
  pull_request:

jobs:
  oxeye-scan:
    name: Oxeye SCAN
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Oxeye Scan
        uses: ox-eye/github-actions/oxeye-scan@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          client-id: ${{ secrets.OXEYE_CICD_CLIENT_ID }}
          secret: ${{ secrets.OXEYE_CICD_SECRET }}
          workspace-id: '5860a390-f5ac-4ea8-88c1-de8c461f7601'
